// Auto-generated pages index
// Handles both named and default exports

// Named exports (export const ComponentName)
export { Login } from './Login';
export { Home } from './Home';
export { Games } from './Games';
export { Dashboard } from './Dashboard';
export { GameSelection } from './GameSelection';
export { AlphabetGame } from './AlphabetGame';
export { AirCanvas } from './AirCanvas';
export { AirGuitarHero } from './AirGuitarHero';
export { AnimalSounds } from './AnimalSounds';
export { BeatBounce } from './BeatBounce';
export { BeginningSounds } from './BeginningSounds';
export { BlendBuilder } from './BlendBuilder';
export { BodyParts } from './BodyParts';
export { BridgeBuilder } from './BridgeBuilder';
export { BubbleBiology } from './BubbleBiology';
export { BubbleCount } from './BubbleCount';
export { BubblePop } from './BubblePop';
export { CatchSort } from './CatchSort';
export { CircuitBuilder } from './CircuitBuilder';
export { ColorMatchGarden } from './ColorMatchGarden';
export { ColorMixing } from './ColorMixing';
export { ColorPotions } from './ColorPotions';
export { ColorSortGame } from './ColorSortGame';
export { ColorSplash } from './ColorSplash';
export { ConnectTheDots } from './ConnectTheDots';
export { CountingCollectathon } from './CountingCollectathon';
export { CountingObjects } from './CountingObjects';
export { CuttingPractice } from './CuttingPractice';
export { DiscoveryLab } from './DiscoveryLab';
export { DinosaurDig } from './DinosaurDig';
export { EarthTimeMachine } from './EarthTimeMachine';
export { EmojiMatch } from './EmojiMatch';
export { EndingSounds } from './EndingSounds';
export { FarmFriends } from './FarmFriends';
export { FeedTheMonster } from './FeedTheMonster';
export { FollowTheLeader } from './FollowTheLeader';
export { ForgotPassword } from './ForgotPassword';
export { FreezeDance } from './FreezeDance';
export { FruitNinjaAir } from './FruitNinjaAir';
export { ISSDocking } from './ISSDocking';
export { KaleidoscopeHands } from './KaleidoscopeHands';
export { LanguagePuppet } from './LanguagePuppet';
export { LetterCatcher } from './LetterCatcher';
export { LetterHunt } from './LetterHunt';
export { LetterSoundMatch } from './LetterSoundMatch';
export { LightPainter } from './LightPainter';
export { LogicBoxPush } from './LogicBoxPush';
export { MazeRunner } from './MazeRunner';
export { MathJumpers } from './MathJumpers';
export { MathMonsters } from './MathMonsters';
export { MathSmash } from './MathSmash';
export { MemoryMatch } from './MemoryMatch';
export { MirrorDraw } from './MirrorDraw';
export { MirrorDuel } from './MirrorDuel';
export { MoneyMatch } from './MoneyMatch';
export { MoreOrLess } from './MoreOrLess';
export { MusicConductor } from './MusicConductor';
export { MusicPinchBeat } from './MusicPinchBeat';
export { MusicalStatues } from './MusicalStatues';
export { NasaSkyHunt } from './NasaSkyHunt';
export { NumberBubblePop } from './NumberBubblePop';
export { NumberSequence } from './NumberSequence';
export { NumberTapTrail } from './NumberTapTrail';
export { NumberTracing } from './NumberTracing';
export { ObstacleCourse } from './ObstacleCourse';
export { OddOneOut } from './OddOneOut';
export { PackLunchbox } from './PackLunchbox';
export { PathFollowing } from './PathFollowing';
export { PatternPlay } from './PatternPlay';
export { PhonicsSounds } from './PhonicsSounds';
export { PhonicsTracing } from './PhonicsTracing';
export { PhysicsPlayground } from './PhysicsPlayground';
export { PinchPractice } from './PinchPractice';
export { PlanetSandbox } from './PlanetSandbox';
export { PlantGarden } from './PlantGarden';
export { PlatformerRunner } from './PlatformerRunner';
export { PopTheNumber } from './PopTheNumber';
export { Pricing } from './Pricing';
export { Progress } from './Progress';
export { RainbowBridge } from './RainbowBridge';
export { ReadingAlong } from './ReadingAlong';
export { ResetPassword } from './ResetPassword';
export { RhymeTime } from './RhymeTime';
export { RhythmTap } from './RhythmTap';
export { SameAndDifferent } from './SameAndDifferent';
export { SetTheTable } from './SetTheTable';
export { ShadowMatch } from './ShadowMatch';
export { ShadowPortal } from './ShadowPortal';
export { ShadowPuppetTheater } from './ShadowPuppetTheater';
export { ShapePop } from './ShapePop';
export { ShapeSafari } from './ShapeSafari';
export { ShapeSequence } from './ShapeSequence';
export { SightWordFlash } from './SightWordFlash';
export { SimonSays } from './SimonSays';
export { SimpleAddition } from './SimpleAddition';
export { SizeSorting } from './SizeSorting';
export { SoundGarden } from './SoundGarden';
export { SpellPainter } from './SpellPainter';
export { SpellingRun } from './SpellingRun';
export { SteadyHandLab } from './SteadyHandLab';
export { StoryBuilder } from './StoryBuilder';
export { SyllableClap } from './SyllableClap';
export { TargetPractice } from './TargetPractice';
export { TasteMatch } from './TasteMatch';
export { TextureExplorer } from './TextureExplorer';
export { TidyUpTime } from './TidyUpTime';
export { VirtualBubbles } from './VirtualBubbles';
export { VirtualChemistryLab } from './VirtualChemistryLab';
export { VoiceStories } from './VoiceStories';
export { WashHandsDance } from './WashHandsDance';
export { WeatherLab } from './WeatherLab';
export { WeatherMatch } from './WeatherMatch';
export { WordBuilder } from './WordBuilder';
export { WordSearch } from './WordSearch';
export { YogaAnimals } from './YogaAnimals';

// Default exports only (not already exported above)
export { default as BalanceBeam } from './BalanceBeam';
export { default as BalloonPopFitness } from './BalloonPopFitness';
export { default as BubblePopSymphony } from './BubblePopSymphony';
export { default as CircleDrawing } from './CircleDrawing';
export { default as ColorByNumber } from './ColorByNumber';
export { default as DressForWeather } from './DressForWeather';
export { default as FingerPaintingMadness } from './FingerPaintingMadness';
export { default as FreeDraw } from './FreeDraw';
export { default as FractionPizza } from './FractionPizza';
export { default as Inventory } from './Inventory';
export { default as MediaPipeTest } from './MediaPipeTest';
export { default as MidlineViolator } from './MidlineViolator';
export { default as MirrorMaze } from './MirrorMaze';
export { default as PrivacyPolicy } from './PrivacyPolicy';
export { Register } from './Register';
export { Settings } from './Settings';
export { default as ShapeStacker } from './ShapeStacker';
export { default as StorySequence } from './StorySequence';
export { default as Support } from './Support';
export { default as TermsOfPlay } from './TermsOfPlay';
export { default as TemperatureSort } from './TemperatureSort';
export { default as TimeTell } from './TimeTell';
export { default as VerifyEmail } from './VerifyEmail';
export { default as VirtualArchery } from './VirtualArchery';
export { default as VowelValley } from './VowelValley';

// 3D games
export { default as BubblePop3D } from './three/BubblePop3D';
export { default as ColorMatchGarden3D } from './three/ColorMatchGarden3D';
export { default as CountingCollectathon3D } from './three/CountingCollectathon3D';
export { default as CuttingPractice3D } from './three/CuttingPractice3D';
export { default as DigitalJenga3D } from './three/DigitalJenga3D';
export { default as DressForWeather3D } from './three/DressForWeather3D';
export { default as FeedTheMonster3D } from './three/FeedTheMonster3D';
export { default as ISSDocking3D } from './three/ISSDocking3D';
export { default as ObstacleCourse3D } from './three/ObstacleCourse3D';
export { default as PatternPop3D2 } from './three/PatternPop3D2';
export { default as ShapePop3D } from './three/ShapePop3D';
export { default as ShapeSafari3D } from './three/ShapeSafari3D';
export { default as VirtualBubbles3D } from './three/VirtualBubbles3D';
