/**
 * Report Export Utilities
 * Generate shareable progress reports for parents
 */

import { ProgressItem, TimeBreakdownSummary, StruggleSummary } from '../types/progress';
import { calculateDailyTimeBreakdown, analyzeStruggles } from './progressCalculations';
import { buildProgressShareUrl } from '../services/growthAttribution';

export interface ReportData {
  childName: string;
  reportDate: string;
  timeBreakdown: TimeBreakdownSummary;
  struggleSummary: StruggleSummary;
  totalActivities: number;
  averageAccuracy: number;
}

function getShareInviteLines(origin?: string): string[] {
  const shareUrl = buildProgressShareUrl(origin);

  return [
    '✨ Want to try the same camera-powered learning games?',
    `Try Advay here: ${shareUrl}`,
  ];
}

/**
 * Generate formatted text report for copying/sharing
 */
export function generateTextReport(data: ReportData, origin?: string): string {
  const { childName, reportDate, timeBreakdown, struggleSummary, totalActivities, averageAccuracy } = data;

  const lines = [
    `📊 ${childName}'s Learning Report`,
    `📅 ${reportDate}`,
    '',
    '⏱️ TIME SUMMARY',
    `• Total this week: ${timeBreakdown.totalMinutesWeek} minutes`,
    `• Daily average: ${timeBreakdown.averageMinutesPerDay} minutes`,
    `• Days over limit: ${timeBreakdown.daysExceededLimit}`,
    '',
    '📈 PROGRESS SUMMARY',
    `• Activities completed: ${totalActivities}`,
    `• Average accuracy: ${Math.round(averageAccuracy)}%`,
    '',
  ];

  // Add struggling items
  if (struggleSummary.needsAttentionCount > 0) {
    lines.push('⚠️ NEEDS PRACTICE');
    struggleSummary.strugglingItems.slice(0, 5).forEach((item) => {
      const attempts = item.effectiveAttempts;
      const score = Math.round(item.item.score);
      lines.push(`• ${item.item.content_id.toUpperCase()}: ${score}% (${attempts} tries)`);
    });
    lines.push('');
  }

  // Add recommendations
  lines.push('💡 RECOMMENDATIONS');
  struggleSummary.recommendations.forEach((rec) => {
    lines.push(`• ${rec}`);
  });

  lines.push('');
  lines.push('🌟 TRY ADVAY');
  getShareInviteLines(origin).forEach((line) => {
    lines.push(line);
  });
  lines.push('');
  lines.push('Generated by Advay Vision Learning');

  return lines.join('\n');
}

/**
 * Generate WhatsApp share link with pre-filled message
 */
export function generateWhatsAppShareUrl(data: ReportData, origin?: string): string {
  const text = generateTextReport(data, origin);
  const encoded = encodeURIComponent(text);
  return `https://wa.me/?text=${encoded}`;
}

/**
 * Download text report as .txt file
 */
export function downloadTextReport(data: ReportData, origin?: string): void {
  const text = generateTextReport(data, origin);
  const blob = new Blob([text], { type: 'text/plain;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${data.childName.replace(/\s+/g, '_')}_progress_${new Date().toISOString().split('T')[0]}.txt`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

/**
 * Generate report data from progress items
 */
export function generateReportData(
  childName: string,
  progress: ProgressItem[],
): ReportData {
  const timeBreakdown = calculateDailyTimeBreakdown(progress, 20);
  const struggleSummary = analyzeStruggles(progress);

  const totalActivities = progress.length;
  const averageAccuracy =
    progress.length > 0
      ? progress.reduce((sum, p) => sum + p.score, 0) / progress.length
      : 0;

  return {
    childName,
    reportDate: new Date().toLocaleDateString('en-US', {
      weekday: 'long',
      year: 'numeric',
      month: 'long',
      day: 'numeric',
    }),
    timeBreakdown,
    struggleSummary,
    totalActivities,
    averageAccuracy,
  };
}

/**
 * Copy report to clipboard
 */
export async function copyReportToClipboard(data: ReportData, origin?: string): Promise<boolean> {
  try {
    const text = generateTextReport(data, origin);
    await navigator.clipboard.writeText(text);
    return true;
  } catch {
    return false;
  }
}
