/**
 * PregenAudioCache — Pre-generated Audio Lookup & Playback
 *
 * Maps known static phrases to pre-generated .wav files served from
 * /audio/pregen/en/manifest.json (generated by scripts/generate_all_audio.ts).
 *
 * This is Tier 1 of the three-tier TTS strategy:
 *   1. PregenAudioCache (instant .wav playback) ← this file
 *   2. Kokoro-82M in-browser (neural TTS for dynamic text)
 *   3. Web Speech API (fallback)
 *
 * The manifest is loaded lazily on first access, so there's no blocking
 * on app startup. Adding a new language is as simple as dropping a new
 * manifest under /audio/pregen/{lang}/manifest.json — no code changes needed.
 */

/** Normalize text for matching: lowercase, collapse whitespace */
function normalizeText(text: string): string {
    return text.toLowerCase().replace(/\s+/g, ' ').trim();
}

// ---------------------------------------------------------------------------
// Internal state
// ---------------------------------------------------------------------------

// phraseMap[lang][normalizedText] = "/audio/pregen/en/<hash>.wav"
const phraseMap: Record<string, Record<string, string>> = {};
// we track promises for languages that are currently loading; entries
// start undefined until the load begins, so make the type optional.
const manifestLoading: Record<string, Promise<void> | undefined> = {};
const audioCache = new Map<string, HTMLAudioElement>();
let currentlyPlaying: HTMLAudioElement | null = null;

// ---------------------------------------------------------------------------
// Manifest loading
// ---------------------------------------------------------------------------

async function loadManifest(lang: string): Promise<void> {
    if (phraseMap[lang]) return; // already loaded
    if (manifestLoading[lang]) return manifestLoading[lang]; // in-flight

    manifestLoading[lang] = (async () => {
        try {
            const response = await fetch(`/audio/pregen/${lang}/manifest.json`);
            if (!response.ok) {
                // No manifest yet — use empty map (graceful degradation)
                console.warn(
                    `[PregenAudioCache] No manifest found for lang "${lang}" (${response.status}). ` +
                    `Run scripts/generate_all_audio.ts to generate audio files.`,
                );
                phraseMap[lang] = {};
                return;
            }
            phraseMap[lang] = await response.json() as Record<string, string>;
            console.log(
                `[PregenAudioCache] Loaded ${Object.keys(phraseMap[lang]).length} entries for lang "${lang}"`,
            );
        } catch (err) {
            console.warn(`[PregenAudioCache] Failed to load manifest for "${lang}":`, err);
            phraseMap[lang] = {};
        }
    })();

    return manifestLoading[lang];
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

export class PregenAudioCache {
    /**
     * Check if a phrase has a pre-generated audio file.
     * NOTE: Returns false if the manifest hasn't been loaded yet.
     * Call preloadAll() on app init to ensure the manifest is ready.
     */
    static has(text: string, lang = 'en'): boolean {
        const map = phraseMap[lang];
        if (!map) return false;
        return normalizeText(text) in map;
    }

    /**
     * Play a pre-generated audio file for the given text.
     * Returns a promise that resolves when playback completes.
     * Throws if the phrase is not in the cache.
     */
    static async play(text: string, volume = 1.0, lang = 'en'): Promise<void> {
        // Ensure manifest is loaded
        await loadManifest(lang);

        const map = phraseMap[lang] ?? {};
        const normalized = normalizeText(text);
        const webPath = map[normalized];

        if (!webPath) {
            return Promise.reject(
                new Error(`[PregenAudioCache] No pre-generated audio for: "${text}"`),
            );
        }

        let audio = audioCache.get(webPath);
        if (!audio) {
            audio = new Audio(webPath);
            audio.preload = 'auto';
            audioCache.set(webPath, audio);
        }

        // Stop anything currently playing
        if (currentlyPlaying && currentlyPlaying !== audio) {
            currentlyPlaying.pause();
            currentlyPlaying.currentTime = 0;
        }

        audio.volume = Math.max(0, Math.min(1, volume));
        audio.currentTime = 0;
        currentlyPlaying = audio;

        return new Promise<void>((resolve, reject) => {
            audio!.onended = () => {
                currentlyPlaying = null;
                resolve();
            };
            audio!.onerror = () =>
                reject(new Error(`[PregenAudioCache] Failed to play: ${webPath}`));
            audio!.play().catch(reject);
        });
    }

    /**
     * Stop any currently playing pre-generated audio.
     */
    static stop(): void {
        if (currentlyPlaying) {
            currentlyPlaying.pause();
            currentlyPlaying.currentTime = 0;
            currentlyPlaying = null;
        }
    }

    /**
     * Preload all audio files for a language (call on app init for instant playback).
     * Loads the manifest and pre-fetches all Audio elements.
     */
    static async preloadAll(lang = 'en'): Promise<void> {
        await loadManifest(lang);
        const map = phraseMap[lang] ?? {};
        let count = 0;
        for (const webPath of Object.values(map)) {
            if (!audioCache.has(webPath)) {
                const audio = new Audio(webPath);
                audio.preload = 'auto';
                audioCache.set(webPath, audio);
                count++;
            }
        }
        if (count > 0) {
            console.log(`[PregenAudioCache] Preloaded ${count} new clips for lang "${lang}"`);
        }
    }

    /** Get count of loaded phrases for a language. */
    static phraseCount(lang = 'en'): number {
        return Object.keys(phraseMap[lang] ?? {}).length;
    }
}

export default PregenAudioCache;
